"""Desktop support helpers for WeisileLink releases."""

from weisile_link.desktop.profiles import (
    DesktopProfile,
    DesktopProfileError,
    DesktopProfileStore,
    MacOSKeychainBackend,
    MemoryCredentialBackend,
    WindowsCredentialManagerBackend,
    credential_backend_for_platform,
    default_config_path,
    resolve_profile_environment,
    save_claimed_profile,
)
from weisile_link.desktop.pairing import (
    DesktopPairingResult,
    DesktopPairingService,
    DesktopReadyCheck,
    build_pairing_parser,
    create_vsle_bluetooth_transport,
    run_pairing_command,
)
from weisile_link.desktop.diagnostics import (
    DesktopDiagnosticCheck,
    DesktopDiagnosticsResult,
    DesktopDiagnosticsService,
    build_diagnostics_bundle,
    build_diagnostics_parser,
    redact_secret_text,
    run_diagnostics_command,
    sanitize_diagnostics_value,
)
from weisile_link.desktop.runtime import (
    DesktopHealthState,
    DesktopRuntimeService,
    DesktopStartupPlan,
    build_desktop_start_parser,
    classroom_allowed_origins,
    run_desktop_start_command,
)
from weisile_link.desktop.supervisor import (
    DesktopSupervisionResult,
    DesktopSupervisorService,
    build_desktop_start_command,
    build_supervisor_parser,
    run_supervisor_command,
    tcp_port_open,
    wait_for_local_ports,
)

__all__ = [
    "DesktopDiagnosticCheck",
    "DesktopDiagnosticsResult",
    "DesktopDiagnosticsService",
    "DesktopHealthState",
    "DesktopPairingResult",
    "DesktopPairingService",
    "DesktopProfile",
    "DesktopProfileError",
    "DesktopProfileStore",
    "DesktopReadyCheck",
    "DesktopRuntimeService",
    "DesktopSupervisionResult",
    "DesktopSupervisorService",
    "DesktopStartupPlan",
    "MacOSKeychainBackend",
    "MemoryCredentialBackend",
    "WindowsCredentialManagerBackend",
    "build_diagnostics_bundle",
    "build_diagnostics_parser",
    "build_desktop_start_parser",
    "build_desktop_start_command",
    "build_pairing_parser",
    "build_supervisor_parser",
    "classroom_allowed_origins",
    "credential_backend_for_platform",
    "create_vsle_bluetooth_transport",
    "default_config_path",
    "redact_secret_text",
    "run_diagnostics_command",
    "run_desktop_start_command",
    "resolve_profile_environment",
    "run_pairing_command",
    "run_supervisor_command",
    "sanitize_diagnostics_value",
    "save_claimed_profile",
    "tcp_port_open",
    "wait_for_local_ports",
]
